apiVersion: v1
kind: Service
metadata:
  name: infrastack-postgres
  namespace: infrastack
spec:
  selector:
    app: data-pipeline
    version: v1
  ports:
    - protocol: TCP
      targetPort: db
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: infrastack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
        version: v1
    spec:
      containers:
        - name: infrastack-postgres
          env:
            - name: POSTGRES_DB
              value: public
            - name: POSTGRES_USER
              value: postgres
          image: postgres:alpine
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          ports:
            - name: db
              containerPort: 5432
      volumes:
        - name: db-data
          emptyDir: {}
