apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: infrastack
spec:
  type: LoadBalancer
  selector:
    app: server # Label selector to communicate with Pods of the same name.
  ports:
    - protocol: TCP
      targetPort: api
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: infrastack
spec:
  replicas: 3 # Number of replicas in the ReplicaSet.
  selector:
    matchLabels:
    # This tells the Deployment to select Pods with this label.
      app: server
  minReadSeconds: 5 # Wait a minimum of 5 seconds afer each update, this gives the Pods a change to update and complete some health checks before moving onto the next replica.
  strategy:
    rollingUpdate:
      maxSurge: 1 # Allow one replica above the desired replicas during an update.
      maxUnvailable: 0 # Never go below this number of replicas.
  template:
    metadata:
      labels:
      # This label is attached to all Pods started by this deployment.
        app: server
        version: v1
    spec:
      containers:
        - name: server
          image: infrastack/server:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /app
              name: hot-reload-server
          ports:
            - name: api
              containerPort: 8080
      volumes:
        - name: hot-reload-server
          hostPath:
            # Path is essentially $(cwd)/server
            path: /path/to/projects/infrastack/server
            type: Directory
